exports.strings = {
  'Attorney': {
    Atlanta: 'https://www.glassdoor.com/Salaries/atlanta-attorney-salary-SRCH_IL.0,7_IM52_KO8,16.htm',
    Austin: 'https://www.glassdoor.com/Salaries/austin-attorney-salary-SRCH_IL.0,6_IM60_KO7,15.htm',
    Baltimore: 'https://www.glassdoor.com/Salaries/baltimore-attorney-salary-SRCH_IL.0,9_IM63_KO10,18.htm',
    Birmingham: 'https://www.glassdoor.com/Salaries/birmingham-attorney-salary-SRCH_IL.0,10_IM93_KO11,19.htm',
    Boston: 'https://www.glassdoor.com/Salaries/boston-attorney-salary-SRCH_IL.0,6_IM109_KO7,15.htm',
    NYC: 'https://www.glassdoor.com/Salaries/new-york-city-attorney-salary-SRCH_IL.0,13_IM615_KO14,22.htm',
    LA: 'https://www.glassdoor.com/Salaries/los-angeles-attorney-salary-SRCH_IL.0,11_IM508_KO12,20.htm'
  },
  'Registered Nurse': {
    _Average: 'https://www.glassdoor.com/Salaries/us-registered-nurse-salary-SRCH_IL.0,2_IN1_KO3,19.htm',
    Atlanta: 'https://www.glassdoor.com/Salaries/atlanta-registered-nurse-salary-SRCH_IL.0,7_IM52_KO8,24.htm',
    Austin: 'https://www.glassdoor.com/Salaries/austin-registered-nurse-salary-SRCH_IL.0,6_IM60_KO7,23.htm',
    Baltimore: 'https://www.glassdoor.com/Salaries/baltimore-registered-nurse-salary-SRCH_IL.0,9_IM63_KO10,26.htm',
    Birmingham: 'https://www.glassdoor.com/Salaries/birmingham-registered-nurse-salary-SRCH_IL.0,10_IM93_KO11,27.htm',
    Boston: 'https://www.glassdoor.com/Salaries/boston-registered-nurse-salary-SRCH_IL.0,6_IM109_KO7,23.htm',
    Buffalo: 'https://www.glassdoor.com/Salaries/buffalo-registered-nurse-salary-SRCH_IL.0,7_IM129_KO8,24.htm',
    Charlotte: 'https://www.glassdoor.com/Salaries/charlotte-registered-nurse-salary-SRCH_IL.0,9_IM162_KO10,26.htm',
    Chicago: 'https://www.glassdoor.com/Salaries/chicago-registered-nurse-salary-SRCH_IL.0,7_IM167_KO8,24.htm',
    Cincinnati: 'https://www.glassdoor.com/Salaries/cincinnati-registered-nurse-salary-SRCH_IL.0,10_IM170_KO11,27.htm',
    Cleveland: 'https://www.glassdoor.com/Salaries/cleveland-registered-nurse-salary-SRCH_IL.0,9_IM179_KO10,26.htm',
    Columbus: 'https://www.glassdoor.com/Salaries/columbus-registered-nurse-salary-SRCH_IL.0,8_IM196_KO9,25.htm',
    DC: 'https://www.glassdoor.com/Salaries/washington-dc-registered-nurse-salary-SRCH_IL.0,13_IM911_KO14,30.htm',
    Dallas: 'https://www.glassdoor.com/Salaries/dallas-registered-nurse-salary-SRCH_IL.0,6_IM218_KO7,23.htm',
    Denver: 'https://www.glassdoor.com/Salaries/denver-registered-nurse-salary-SRCH_IL.0,6_IM234_KO7,23.htm',
    Detroit: 'https://www.glassdoor.com/Salaries/detroit-registered-nurse-salary-SRCH_IL.0,7_IM236_KO8,24.htm',
    Hartford: 'https://www.glassdoor.com/Salaries/hartford-registered-nurse-salary-SRCH_IL.0,8_IM372_KO9,25.htm',
    Houston: 'https://www.glassdoor.com/Salaries/houston-registered-nurse-salary-SRCH_IL.0,7_IM394_KO8,24.htm',
    Indianapolis: 'https://www.glassdoor.com/Salaries/indianapolis-registered-nurse-salary-SRCH_IL.0,12_IM407_KO13,29.htm',
    Jacksonville: 'https://www.glassdoor.com/Salaries/jacksonville-registered-nurse-salary-SRCH_IL.0,12_IM416_KO13,29.htm',
    KC: 'https://www.glassdoor.com/Salaries/kansas-city-registered-nurse-salary-SRCH_IL.0,11_IM437_KO12,28.htm',
    LA: 'https://www.glassdoor.com/Salaries/los-angeles-registered-nurse-salary-SRCH_IL.0,11_IM508_KO12,28.htm',
    LasVegas: 'https://www.glassdoor.com/Salaries/las-vegas-registered-nurse-salary-SRCH_IL.0,9_IM477_KO10,26.htm',
    Louisville: 'https://www.glassdoor.com/Salaries/louisville-registered-nurse-salary-SRCH_IL.0,10_IM509_KO11,27.htm',
    Memphis: 'https://www.glassdoor.com/Salaries/memphis-registered-nurse-salary-SRCH_IL.0,7_IM551_KO8,24.htm',
    Miami: 'https://www.glassdoor.com/Salaries/miami-registered-nurse-salary-SRCH_IL.0,5_IM558_KO6,22.htm',
    Milwaukee: 'https://www.glassdoor.com/Salaries/milwaukee-registered-nurse-salary-SRCH_IL.0,9_IM564_KO10,26.htm',
    Minneapolis: 'https://www.glassdoor.com/Salaries/minneapolis-registered-nurse-salary-SRCH_IL.0,11_IM567_KO12,28.htm',
    Nashville: 'https://www.glassdoor.com/Salaries/nashville-registered-nurse-salary-SRCH_IL.0,9_IM604_KO10,26.htm',
    NewOrleans: 'https://www.glassdoor.com/Salaries/new-orleans-registered-nurse-salary-SRCH_IL.0,11_IM612_KO12,28.htm',
    NYC: 'https://www.glassdoor.com/Salaries/new-york-city-registered-nurse-salary-SRCH_IL.0,13_IM615_KO14,30.htm',
    OklahomaCity: 'https://www.glassdoor.com/Salaries/oklahoma-city-registered-nurse-salary-SRCH_IL.0,13_IM637_KO14,30.htm',
    Orlando: 'https://www.glassdoor.com/Salaries/orlando-registered-nurse-salary-SRCH_IL.0,7_IM645_KO8,24.htm',
    Philly: 'https://www.glassdoor.com/Salaries/philadelphia-registered-nurse-salary-SRCH_IL.0,12_IM676_KO13,29.htm',
    Phoenix: 'https://www.glassdoor.com/Salaries/phoenix-registered-nurse-salary-SRCH_IL.0,7_IM678_KO8,24.htm',
    Pittsburgh: 'https://www.glassdoor.com/Salaries/pittsburgh-registered-nurse-salary-SRCH_IL.0,10_IM684_KO11,27.htm',
    Portland: 'https://www.glassdoor.com/Salaries/portland-registered-nurse-salary-SRCH_IL.0,8_IM699_KO9,25.htm',
    Providence: 'https://www.glassdoor.com/Salaries/providence-registered-nurse-salary-SRCH_IL.0,10_IM707_KO11,27.htm',
    Raleigh: 'https://www.glassdoor.com/Salaries/raleigh-registered-nurse-salary-SRCH_IL.0,7_IM714_KO8,24.htm',
    Richmond: 'https://www.glassdoor.com/Salaries/richmond-registered-nurse-salary-SRCH_IL.0,8_IM724_KO9,25.htm',
    Riverside: 'https://www.glassdoor.com/Salaries/riverside-registered-nurse-salary-SRCH_IL.0,9_IM727_KO10,26.htm',
    SF: 'https://www.glassdoor.com/Salaries/san-francisco-registered-nurse-salary-SRCH_IL.0,13_IM759_KO14,30.htm',
    Sacramento: 'https://www.glassdoor.com/Salaries/sacramento-registered-nurse-salary-SRCH_IL.0,10_IM747_KO11,27.htm',
    SaltLakeCity: 'https://www.glassdoor.com/Salaries/salt-lake-city-registered-nurse-salary-SRCH_IL.0,14_IM755_KO15,31.htm',
    SanAntonio: 'https://www.glassdoor.com/Salaries/san-antonio-registered-nurse-salary-SRCH_IL.0,11_IM757_KO12,28.htm',
    SanDiego: 'https://www.glassdoor.com/Salaries/san-diego-registered-nurse-salary-SRCH_IL.0,9_IM758_KO10,26.htm',
    SanJose: 'https://www.glassdoor.com/Salaries/san-jose-registered-nurse-salary-SRCH_IL.0,8_IM761_KO9,25.htm',
    Seattle: 'https://www.glassdoor.com/Salaries/seattle-registered-nurse-salary-SRCH_IL.0,7_IC1150505_KO8,24.htm',
    StLouis: 'https://www.glassdoor.com/Salaries/st-louis-registered-nurse-salary-SRCH_IL.0,8_IM823_KO9,25.htm',
    Tampa: 'https://www.glassdoor.com/Salaries/tampa-registered-nurse-salary-SRCH_IL.0,5_IM850_KO6,22.htm',
    VirginiaBeach: 'https://www.glassdoor.com/Salaries/virginia-beach-registered-nurse-salary-SRCH_IL.0,14_IC1130324_KO15,31.htm'
  },
  'Software Engineer': {
    Atlanta: 'https://www.glassdoor.com/Salaries/atlanta-software-engineer-salary-SRCH_IL.0,7_IM52_KO8,25.htm',
    Austin: 'https://www.glassdoor.com/Salaries/austin-software-engineer-salary-SRCH_IL.0,6_IM60_KO7,24.htm',
    Baltimore: 'https://www.glassdoor.com/Salaries/baltimore-software-engineer-salary-SRCH_IL.0,9_IM63_KO10,27.htm',
    Birmingham: 'https://www.glassdoor.com/Salaries/birmingham-software-engineer-salary-SRCH_IL.0,10_IM93_KO11,28.htm',
    Boston: 'https://www.glassdoor.com/Salaries/boston-software-engineer-salary-SRCH_IL.0,6_IM109_KO7,24.htm',
    NYC: 'https://www.glassdoor.com/Salaries/new-york-city-software-engineer-salary-SRCH_IL.0,13_IM615_KO14,31.htm',
    LA: 'https://www.glassdoor.com/Salaries/los-angeles-software-engineer-salary-SRCH_IL.0,11_IM508_KO12,29.htm'
  }
}